server:
  port: 9090
spring:
  cache:
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=600s

# graphql
graphql:
  spqr:
    gui:
      enabled: true
    base-packages:
      - org.opennms.horizon.shared.dto

# keycloak admin client properties
horizon-stream:
  core:
    url: http://localhost:8181

logging:
  file.path: /var/log/restServer
