POST http://localhost:8080/employees
Content-Type: application/json

{
  "first_name": "Yang",
  "last_name" : "Li",
  "gender": "M",
  "birth_date": "1965-01-23",
  "hire_date" : "2021-06-01"

}

###
PUT http://localhost:8080/employees
Content-Type: application/json

{
  "id" : 1,
  "first_name": "Yang-updated",
  "last_name" : "Li",
  "gender": "M",
  "birth_date": "1965-01-23",
  "hire_date" : "2021-06-01",
  "department": {
    "name": "HR"
  }

}