# your helm chart values here
Operator:
  image: opennms/operator:bleeding
  resources:
    limits:
      cpu: 0
      memory: 50Mi
    requests:
      cpu: 0
      memory: 50Mi
TLS:
  Enabled: false
Prometheus:
  Server:
    ServiceName: prometheus
    Image: prom/prometheus
  PushGateway:
    ServiceName: prometheus-pushgateway
    Image: prom/pushgateway
